### ISSUE TITLE
Tech checklist

### ISSUE THREAD

**Issue by lepelog** [bingothon/bingothon-layouts#26]
- [x] List containing all actions the tech has to do before a run starts
- [ ] List depends on type of the next run (for example some runs (like Ori) are speacial)
- [ ] Steps get auto marked when done (not sure, would work for connecting the next bingoboard for example)
- [ ] Send hosts a message once tech is ready, so they can send a message back when they're ready as well

**Comment by Floha258** [comment]
If we go with auto check, we need to make sure it doesn't get checked too early (for example, don't just check on existing connection for bingoboard, when it's still connected to the old room)

**Comment by lepelog** [comment]
works good enough for now
